### ISSUE TITLE
TypeError: object of type 'int' has no len(). When using get_led_colors_by_device_index

### ISSUE THREAD

**Issue by ModdedManiac013** [CorsairOfficial/cue-sdk-python#8]
I was trying to run get_led_colors_by_device_index to get the color from my mouse to then send to an LED Strip, but encountered this error:
```
Traceback (most recent call last):
  File "C:/Users/Modded/Desktop/MagHomeCue.py", line 6, in <module>
    print(sdk.get_led_colors_by_device_index(0, CorsairLedId.M_2))
  File "C:\Users\Modded\PycharmProjects\pythonProject1\venv\lib\site-packages\cuesdk\api.py", line 236, in get_led_colors_by_device_index
    sz = len(led_identifiers)
TypeError: object of type 'int' has no len()
```
The following is a copy of how I was using the command:
```python
from cuesdk import *

sdk = CueSdk()
sdk.connect()

print(sdk.get_led_colors_by_device_index(0, CorsairLedId.M_2))
```

**Comment by intrueder** [comment]
That's because the second argument must be a `list` (read more: [api_reference.md](https://github.com/CorsairOfficial/cue-sdk-python/blob/master/api_reference.md#method-get_led_colors_by_device_index))

Try this:

```py
print(sdk.get_led_colors_by_device_index(0, [CorsairLedId.M_2]))
```

**Comment by ModdedManiac013** [comment]
Awesome that fixed it thank you very much.
